apiVersion: v2
publisher: dmka
name: dmka
version: 1.0.0
type: VS Code extension
displayName: dmka
title: dmka VS Extension
description: dmka into your 
icon: https://github.com/tabeyti/jenkins-jack/blob/master/images/logo.svg
repository: https://github.com/xkardim/che
category: Other
firstPublicationDate: "2019-07-08"
spec:
  containers:
     name: vscode-python
     memoryLimit: 512Mi
     memoryRequest: 20Mi
     cpuLimit: 500m
     cpuRequest: 30m
     volumeMounts:
      - name: venv
        path: /home/theia/.venv
     image: 'docker.io/xkardim/cheimage:7'
  extensions:
    - https://github.com/microsoft/vscode-python/releases/download/2020.7.94776/ms-python-release.vsix
