apiVersion: v2
publisher: ms
name: python_python
version: latest
type: VS Code extension
displayName: dmka
title: dmka VS Extension
description: dmka into your 
icon: https://github.com/tabeyti/jenkins-jack/blob/master/images/logo.svg
repository: https://github.com/xkardim/che
category: Other
firstPublicationDate: "2019-07-08"
spec:
  containers:                                                   
    - image: xkardim/cheimage:7
  extensions:
    - https://github.com/microsoft/vscode-python/releases/download/2020.7.94776/ms-python-release.vsix
